<a href="https://colab.research.google.com/github/talibaisi/MachineLearning/blob/main/Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from pandas import read_csv
headernames = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

print('Hello Python')

Hello Python


In [10]:
data = read_csv('/content/pima-indians-diabetes.csv')

In [11]:
data.shape

(768, 9)

In [12]:
data.dtypes

preg       int64
plas       int64
pres       int64
skin       int64
test       int64
mass     float64
pedi     float64
age        int64
class      int64
dtype: object

In [15]:
from pandas import set_option
set_option('display.width', 100)
set_option('precision', 2)
print(data.shape)
data.describe()

(768, 9)


preg    plas    pres    skin    test    mass    pedi     age   class
count  768.00  768.00  768.00  768.00  768.00  768.00  768.00  768.00  768.00
mean     3.85  120.89   69.11   20.54   79.80   31.99    0.47   33.24    0.35
std      3.37   31.97   19.36   15.95  115.24    7.88    0.33   11.76    0.48
min      0.00    0.00    0.00    0.00    0.00    0.00    0.08   21.00    0.00
25%      1.00   99.00   62.00    0.00    0.00   27.30    0.24   24.00    0.00
50%      3.00  117.00   72.00   23.00   30.50   32.00    0.37   29.00    0.00
75%      6.00  140.25   80.00   32.00  127.25   36.60    0.63   41.00    1.00
max     17.00  199.00  122.00   99.00  846.00   67.10    2.42   81.00    1.00

In [17]:
count_class = data.groupby('class').size()
print(count_class)
data.groupby('class').size()

class
0    500
1    268
dtype: int64


class
0    500
1    268
dtype: int64

In [24]:
correlations = data.corr(method='pearson')
print(correlations)


       preg  plas  pres  skin  test  mass  pedi   age  class
preg   1.00  0.13  0.14 -0.08 -0.07  0.02 -0.03  0.54   0.22
plas   0.13  1.00  0.15  0.06  0.33  0.22  0.14  0.26   0.47
pres   0.14  0.15  1.00  0.21  0.09  0.28  0.04  0.24   0.07
skin  -0.08  0.06  0.21  1.00  0.44  0.39  0.18 -0.11   0.07
test  -0.07  0.33  0.09  0.44  1.00  0.20  0.19 -0.04   0.13
mass   0.02  0.22  0.28  0.39  0.20  1.00  0.14  0.04   0.29
pedi  -0.03  0.14  0.04  0.18  0.19  0.14  1.00  0.03   0.17
age    0.54  0.26  0.24 -0.11 -0.04  0.04  0.03  1.00   0.24
class  0.22  0.47  0.07  0.07  0.13  0.29  0.17  0.24   1.00


In [19]:
print(data.skew())


preg     0.90
plas     0.17
pres    -1.84
skin     0.11
test     2.27
mass    -0.43
pedi     1.92
age      1.13
class    0.64
dtype: float64


In [32]:
from numpy import set_printoptions
from numpy import set_printoptions
from sklearn import preprocessing
#Scaling
array = data.values
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_rescaled = data_scaler.fit_transform(array)
set_printoptions(precision=1)
print ("\nScaled data:\n", data_rescaled[0:10])



Scaled data:
 [[0.4 0.7 0.6 0.4 0.  0.5 0.2 0.5 1. ]
 [0.1 0.4 0.5 0.3 0.  0.4 0.1 0.2 0. ]
 [0.5 0.9 0.5 0.  0.  0.3 0.3 0.2 1. ]
 [0.1 0.4 0.5 0.2 0.1 0.4 0.  0.  0. ]
 [0.  0.7 0.3 0.4 0.2 0.6 0.9 0.2 1. ]
 [0.3 0.6 0.6 0.  0.  0.4 0.1 0.2 0. ]
 [0.2 0.4 0.4 0.3 0.1 0.5 0.1 0.1 1. ]
 [0.6 0.6 0.  0.  0.  0.5 0.  0.1 0. ]
 [0.1 1.  0.6 0.5 0.6 0.5 0.  0.5 1. ]
 [0.5 0.6 0.8 0.  0.  0.  0.1 0.6 1. ]]


In [36]:
#Normalization
from sklearn.preprocessing import Normalizer
array = data.values
data_norm = Normalizer(norm='l2').fit(array)
result = data_norm.transform(array)
set_printoptions(precision=2)
print('\nNormalized Data',result[0:10])


Normalized Data [[3.36e-02 8.28e-01 4.03e-01 1.96e-01 0.00e+00 1.88e-01 3.51e-03 2.80e-01
  5.59e-03]
 [8.42e-03 7.16e-01 5.56e-01 2.44e-01 0.00e+00 2.24e-01 2.96e-03 2.61e-01
  0.00e+00]
 [4.04e-02 9.24e-01 3.23e-01 0.00e+00 0.00e+00 1.18e-01 3.39e-03 1.62e-01
  5.05e-03]
 [6.61e-03 5.88e-01 4.36e-01 1.52e-01 6.22e-01 1.86e-01 1.10e-03 1.39e-01
  0.00e+00]
 [0.00e+00 5.96e-01 1.74e-01 1.52e-01 7.31e-01 1.88e-01 9.96e-03 1.44e-01
  4.35e-03]
 [3.49e-02 8.10e-01 5.17e-01 0.00e+00 0.00e+00 1.79e-01 1.40e-03 2.09e-01
  0.00e+00]
 [2.18e-02 5.66e-01 3.63e-01 2.32e-01 6.38e-01 2.25e-01 1.80e-03 1.89e-01
  7.25e-03]
 [8.06e-02 9.26e-01 0.00e+00 0.00e+00 0.00e+00 2.84e-01 1.08e-03 2.34e-01
  0.00e+00]
 [3.41e-03 3.36e-01 1.19e-01 7.67e-02 9.25e-01 5.20e-02 2.69e-04 9.03e-02
  1.70e-03]
 [4.80e-02 7.49e-01 5.76e-01 0.00e+00 0.00e+00 0.00e+00 1.39e-03 3.24e-01
  6.00e-03]]


In [38]:
from sklearn.preprocessing import Binarizer
data_binarized = Binarizer(threshold=0.5).fit(array).transform(array)
print('\nBinarized Data: ',data_binarized[0:10])


Binarized Data:  [[1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 1. 1.]]


In [40]:
from sklearn.preprocessing import StandardScaler

data_scaled2 = StandardScaler().fit(array).transform(array)
print('\nStandard Scaled Data:',data_scaled2[0:10])


Standard Scaled Data: [[ 0.64  0.85  0.15  0.91 -0.69  0.2   0.47  1.43  1.37]
 [-0.84 -1.12 -0.16  0.53 -0.69 -0.68 -0.37 -0.19 -0.73]
 [ 1.23  1.94 -0.26 -1.29 -0.69 -1.1   0.6  -0.11  1.37]
 [-0.84 -1.   -0.16  0.15  0.12 -0.49 -0.92 -1.04 -0.73]
 [-1.14  0.5  -1.5   0.91  0.77  1.41  5.48 -0.02  1.37]
 [ 0.34 -0.15  0.25 -1.29 -0.69 -0.81 -0.82 -0.28 -0.73]
 [-0.25 -1.34 -0.99  0.72  0.07 -0.13 -0.68 -0.62  1.37]
 [ 1.83 -0.18 -3.57 -1.29 -0.69  0.42 -1.02 -0.36 -0.73]
 [-0.55  2.38  0.05  1.53  4.02 -0.19 -0.95  1.68  1.37]
 [ 1.23  0.13  1.39 -1.29 -0.69 -4.06 -0.72  1.77  1.37]]


# New Section