In [1]:
import numpy as np
np.array([1,2,3])
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [2]:
x = np.array(
    [[1,2,3],[4,5,6],[7,8,9]]
)

In [3]:
from scipy import sparse
matrix = np.array(
    [
        [0,1],[3,0],[0,8]
    ]
)

compressed_mat = sparse.csr_matrix(matrix)
print(compressed_mat)

  (0, 1)	1
  (1, 0)	3
  (2, 1)	8


In [4]:
x[1][1]
x.size
add1000 = lambda i: i +1000
x_added1000 = np.vectorize(add1000)
x_added1000(x)

x.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [5]:
np.random.seed(10)
np.random.random(4)
np.random.uniform(3,4,10)
np.random.normal(0.0,1.0,3)

array([ 0.43302619,  1.20303737, -0.96506567])

In [6]:
np.random.logistic(0.0,1.0,3)

array([2.41248124, 0.9177125 , 0.17058997])

In [7]:
from sklearn import datasets
digits = datasets.load_digits()
np2dimData = digits.data
np2dimData.reshape(-1)
np2dimData.shape
np2dimData[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [8]:
from sklearn.datasets import make_regression
# Generate features matrix, target vector, and the true coefficients
features, target, coefficients = make_regression(n_samples = 100,
n_features = 3,
n_informative = 3,
n_targets = 1,
noise = 0.0,
coef = True,
random_state = 1)

In [9]:
# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [10]:
from sklearn.datasets import make_classification
# Generate features matrix and target vector
features, target = make_classification(n_samples = 100,
n_features = 3,
n_informative = 3,
n_redundant = 0,
n_classes = 2,
weights = [.25, .75],
random_state = 1)

In [11]:
# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target Vector
 [1 0 0]


In [12]:
# Load library
from sklearn.datasets import make_blobs
# Generate feature matrix and target vector
features, target = make_blobs(n_samples = 100,
n_features = 2,
centers = 3,
cluster_std = 0.5,
shuffle = True,
random_state = 1)
# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ -1.22685609   3.25572052]
 [ -9.57463218  -4.38310652]
 [-10.71976941  -4.20558148]]
Target Vector
 [0 1 1]


In [43]:
data1 = pd.DataFrame(data= np.c_[digits['data'], digits['target']],
                     columns= [digits['feature_names'] + ['target']])


In [47]:
boston = datasets.load_boston()


In [53]:
df_boston = pd.DataFrame(boston.data,columns=boston.feature_names)
df_boston['target'] = pd.Series(boston.target)
df_boston[(df_boston['ZN'] > 0) & (df_boston['AGE'] > 20)].head()
df_boston['CRIM'].replace(0.00632,0.1)

0      0.10000
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64

In [56]:
import pandas as pd
df_aug = pd.read_csv('aug_train.csv')
df_aug.describe()

enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [57]:
df_aug.nunique()

enrollee_id               19158
city                        123
city_development_index       93
gender                        3
relevent_experience           2
enrolled_university           3
education_level               5
major_discipline              6
experience                   22
company_size                  8
company_type                  6
last_new_job                  6
training_hours              241
target                        2
dtype: int64

In [59]:
df_aug['city'].value_counts()

city_103    4355
city_21     2702
city_16     1533
city_114    1336
city_160     845
            ... 
city_129       3
city_121       3
city_111       3
city_171       1
city_140       1
Name: city, Length: 123, dtype: int64

In [67]:
df_aug[df_aug.company_type.isnull()]

enrollee_id      city  city_development_index gender  \
0             8949  city_103                   0.920   Male   
2            11561   city_21                   0.624    NaN   
5            21651  city_176                   0.764    NaN   
10           29452   city_21                   0.624    NaN   
13            5826   city_21                   0.624   Male   
...            ...       ...                     ...    ...   
19144        17191   city_21                   0.624    NaN   
19151        11385  city_149                   0.689   Male   
19153         7386  city_173                   0.878   Male   
19154        31398  city_103                   0.920   Male   
19157        23834   city_67                   0.855    NaN   

           relevent_experience enrolled_university education_level  \
0      Has relevent experience       no_enrollment        Graduate   
2       No relevent experience    Full time course        Graduate   
5      Has relevent experience    Part time course        Graduate   
10      No relevent experience    Full time course     High School   
13      No relevent experience                 NaN             NaN   
...                        ...                 ...             ...   
19144   No relevent experience    Full time course        Graduate   
19151   No relevent experience    Full time course        Graduate   
19153   No relevent experience       no_enrollment        Graduate   
19154  Has relevent experience       no_enrollment        Graduate   
19157   No relevent experience       no_enrollment  Primary School   

      major_discipline experience company_size company_type last_new_job  \
0                 STEM        >20          NaN          NaN            1   
2                 STEM          5          NaN          NaN        never   
5                 STEM         11          NaN          NaN            1   
10                 NaN          2          NaN          NaN        never   
13                 NaN          2          NaN          NaN        never   
...                ...        ...          ...          ...          ...   
19144             STEM          4          NaN          NaN        never   
19151              NaN          2          NaN          NaN            1   
19153       Humanities         14          NaN          NaN            1   
19154             STEM         14          NaN          NaN            4   
19157              NaN          2          NaN          NaN            1   

       training_hours  target  
0                  36     1.0  
2                  83     0.0  
5                  24     1.0  
10                 32     1.0  
13                 24     0.0  
...               ...     ...  
19144              48     1.0  
19151              60     0.0  
19153              42     1.0  
19154              52     1.0  
19157             127     0.0  

[6140 rows x 14 columns]

In [69]:
df_aug.drop('company_type',axis=1)

enrollee_id      city  city_development_index gender  \
0             8949  city_103                   0.920   Male   
1            29725   city_40                   0.776   Male   
2            11561   city_21                   0.624    NaN   
3            33241  city_115                   0.789    NaN   
4              666  city_162                   0.767   Male   
...            ...       ...                     ...    ...   
19153         7386  city_173                   0.878   Male   
19154        31398  city_103                   0.920   Male   
19155        24576  city_103                   0.920   Male   
19156         5756   city_65                   0.802   Male   
19157        23834   city_67                   0.855    NaN   

           relevent_experience enrolled_university education_level  \
0      Has relevent experience       no_enrollment        Graduate   
1       No relevent experience       no_enrollment        Graduate   
2       No relevent experience    Full time course        Graduate   
3       No relevent experience                 NaN        Graduate   
4      Has relevent experience       no_enrollment         Masters   
...                        ...                 ...             ...   
19153   No relevent experience       no_enrollment        Graduate   
19154  Has relevent experience       no_enrollment        Graduate   
19155  Has relevent experience       no_enrollment        Graduate   
19156  Has relevent experience       no_enrollment     High School   
19157   No relevent experience       no_enrollment  Primary School   

      major_discipline experience company_size last_new_job  training_hours  \
0                 STEM        >20          NaN            1              36   
1                 STEM         15        50-99           >4              47   
2                 STEM          5          NaN        never              83   
3      Business Degree         <1          NaN        never              52   
4                 STEM        >20        50-99            4               8   
...                ...        ...          ...          ...             ...   
19153       Humanities         14          NaN            1              42   
19154             STEM         14          NaN            4              52   
19155             STEM        >20        50-99            4              44   
19156              NaN         <1      500-999            2              97   
19157              NaN          2          NaN            1             127   

       target  
0         1.0  
1         0.0  
2         0.0  
3         1.0  
4         0.0  
...       ...  
19153     1.0  
19154     1.0  
19155     0.0  
19156     0.0  
19157     0.0  

[19158 rows x 13 columns]

In [70]:
df_aug.columns

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

In [71]:
df_aug.index

RangeIndex(start=0, stop=19158, step=1)

In [72]:
df_aug.drop_duplicates()

enrollee_id      city  city_development_index gender  \
0             8949  city_103                   0.920   Male   
1            29725   city_40                   0.776   Male   
2            11561   city_21                   0.624    NaN   
3            33241  city_115                   0.789    NaN   
4              666  city_162                   0.767   Male   
...            ...       ...                     ...    ...   
19153         7386  city_173                   0.878   Male   
19154        31398  city_103                   0.920   Male   
19155        24576  city_103                   0.920   Male   
19156         5756   city_65                   0.802   Male   
19157        23834   city_67                   0.855    NaN   

           relevent_experience enrolled_university education_level  \
0      Has relevent experience       no_enrollment        Graduate   
1       No relevent experience       no_enrollment        Graduate   
2       No relevent experience    Full time course        Graduate   
3       No relevent experience                 NaN        Graduate   
4      Has relevent experience       no_enrollment         Masters   
...                        ...                 ...             ...   
19153   No relevent experience       no_enrollment        Graduate   
19154  Has relevent experience       no_enrollment        Graduate   
19155  Has relevent experience       no_enrollment        Graduate   
19156  Has relevent experience       no_enrollment     High School   
19157   No relevent experience       no_enrollment  Primary School   

      major_discipline experience company_size    company_type last_new_job  \
0                 STEM        >20          NaN             NaN            1   
1                 STEM         15        50-99         Pvt Ltd           >4   
2                 STEM          5          NaN             NaN        never   
3      Business Degree         <1          NaN         Pvt Ltd        never   
4                 STEM        >20        50-99  Funded Startup            4   
...                ...        ...          ...             ...          ...   
19153       Humanities         14          NaN             NaN            1   
19154             STEM         14          NaN             NaN            4   
19155             STEM        >20        50-99         Pvt Ltd            4   
19156              NaN         <1      500-999         Pvt Ltd            2   
19157              NaN          2          NaN             NaN            1   

       training_hours  target  
0                  36     1.0  
1                  47     0.0  
2                  83     0.0  
3                  52     1.0  
4                   8     0.0  
...               ...     ...  
19153              42     1.0  
19154              52     1.0  
19155              44     0.0  
19156              97     0.0  
19157             127     0.0  

[19158 rows x 14 columns]

In [74]:
df_aug.drop_duplicates(subset='company_type')

enrollee_id      city  city_development_index  gender  \
0          8949  city_103                   0.920    Male   
1         29725   city_40                   0.776    Male   
4           666  city_162                   0.767    Male   
35         4866  city_103                   0.920    Male   
36        12726  city_114                   0.926    Male   
40         2547  city_114                   0.926  Female   
94        18099  city_103                   0.920     NaN   

        relevent_experience enrolled_university education_level  \
0   Has relevent experience       no_enrollment        Graduate   
1    No relevent experience       no_enrollment        Graduate   
4   Has relevent experience       no_enrollment         Masters   
35  Has relevent experience       no_enrollment        Graduate   
36   No relevent experience    Part time course     High School   
40  Has relevent experience    Full time course         Masters   
94  Has relevent experience       no_enrollment        Graduate   

   major_discipline experience company_size         company_type last_new_job  \
0              STEM        >20          NaN                  NaN            1   
1              STEM         15        50-99              Pvt Ltd           >4   
4              STEM        >20        50-99       Funded Startup            4   
35             STEM         10        10/49  Early Stage Startup            2   
36              NaN          1       10000+                Other            1   
40             STEM         16    1000-4999        Public Sector            2   
94             STEM         10      100-500                  NGO            1   

    training_hours  target  
0               36     1.0  
1               47     0.0  
4                8     0.0  
35             206     0.0  
36             152     0.0  
40              14     0.0  
94              48     0.0

In [77]:
df_aug.groupby(['education_level','enrolled_university'])['training_hours'].mean()

education_level  enrolled_university
Graduate         Full time course       64.368945
                 Part time course       66.725765
                 no_enrollment          65.926014
High School      Full time course       67.766204
                 Part time course       73.795181
                 no_enrollment          64.843617
Masters          Full time course       60.750449
                 Part time course       63.897059
                 no_enrollment          63.639696
Phd              Full time course       48.080000
                 Part time course       34.333333
                 no_enrollment          69.773585
Primary School   Full time course       51.939394
                 Part time course       66.727273
                 no_enrollment          63.776471
Name: training_hours, dtype: float64

In [80]:
time_index = pd.date_range('10/10/2010',periods=100000,freq='30S')
dataframe_a = pd.DataFrame(index = time_index)
dataframe_a['Sale_Amount'] = np.random.randint(1,10,100000)
dataframe_a.resample('W').sum()

Sale_Amount
2010-10-10        14363
2010-10-17       101158
2010-10-24       100954
2010-10-31       101111
2010-11-07       101275
2010-11-14        82331

In [87]:
for name in df_aug['gender'][0:1]:
    print(name.upper())

MALE


In [88]:
df_aug.groupby('gender').apply(lambda x:x.count())

enrollee_id   city  city_development_index  gender  \
gender                                                       
Female         1238   1238                    1238    1238   
Male          13221  13221                   13221   13221   
Other           191    191                     191     191   

        relevent_experience  enrolled_university  education_level  \
gender                                                              
Female                 1238                 1218             1230   
Male                  13221                13041            12979   
Other                   191                  178              182   

        major_discipline  experience  company_size  company_type  \
gender                                                             
Female              1159        1237           902           878   
Male               11370       13209          9323          9231   
Other                143         188           112           108   

        last_new_job  training_hours  target  
gender                                        
Female          1232            1238    1238  
Male           13153           13221   13221  
Other            191             191     191

In [90]:
df_aug['Outliers'] = np.where(df_aug['training_hours'] > 200,1,0)

In [92]:
df_aug[df_aug['Outliers'] > 0]

enrollee_id      city  city_development_index  gender  \
35            4866  city_103                   0.920    Male   
69            4830   city_90                   0.698     NaN   
89           32401  city_103                   0.920  Female   
110           4789   city_67                   0.855    Male   
119          14199  city_160                   0.920    Male   
...            ...       ...                     ...     ...   
19082        22375  city_101                   0.558     NaN   
19100        16368   city_65                   0.802     NaN   
19107        15133  city_160                   0.920    Male   
19117         3458  city_114                   0.926    Male   
19118        12211  city_126                   0.479     NaN   

           relevent_experience enrolled_university education_level  \
35     Has relevent experience       no_enrollment        Graduate   
69      No relevent experience                 NaN             NaN   
89     Has relevent experience       no_enrollment        Graduate   
110    Has relevent experience       no_enrollment        Graduate   
119    Has relevent experience    Part time course        Graduate   
...                        ...                 ...             ...   
19082  Has relevent experience       no_enrollment        Graduate   
19100   No relevent experience       no_enrollment             NaN   
19107   No relevent experience    Part time course        Graduate   
19117  Has relevent experience       no_enrollment         Masters   
19118   No relevent experience       no_enrollment             NaN   

      major_discipline experience company_size         company_type  \
35                STEM         10        10/49  Early Stage Startup   
69                 NaN          2          NaN              Pvt Ltd   
89                STEM          6      100-500                  NaN   
110               STEM          8        50-99              Pvt Ltd   
119    Business Degree         10        50-99       Funded Startup   
...                ...        ...          ...                  ...   
19082             STEM        >20          NaN                  NaN   
19100              NaN          4          NaN                  NaN   
19107             STEM          3          NaN                  NaN   
19117             STEM        >20          NaN                  NaN   
19118              NaN          1          NaN                  NaN   

      last_new_job  training_hours  target  Outliers  
35               2             206     0.0         1  
69           never             228     1.0         1  
89               1             332     0.0         1  
110              1             210     0.0         1  
119              1             260     0.0         1  
...            ...             ...     ...       ...  
19082            1             266     1.0         1  
19100            2             304     0.0         1  
19107            1             322     1.0         1  
19117           >4             214     0.0         1  
19118        never             316     1.0         1  

[802 rows x 15 columns]

In [94]:
df_aug.dropna(axis=0)

enrollee_id      city  city_development_index  gender  \
1            29725   city_40                   0.776    Male   
4              666  city_162                   0.767    Male   
7              402   city_46                   0.762    Male   
8            27107  city_103                   0.920    Male   
11           23853  city_103                   0.920    Male   
...            ...       ...                     ...     ...   
19147        21319   city_21                   0.624    Male   
19149          251  city_103                   0.920    Male   
19150        32313  city_160                   0.920  Female   
19152        29754  city_103                   0.920  Female   
19155        24576  city_103                   0.920    Male   

           relevent_experience enrolled_university education_level  \
1       No relevent experience       no_enrollment        Graduate   
4      Has relevent experience       no_enrollment         Masters   
7      Has relevent experience       no_enrollment        Graduate   
8      Has relevent experience       no_enrollment        Graduate   
11     Has relevent experience       no_enrollment        Graduate   
...                        ...                 ...             ...   
19147   No relevent experience    Full time course        Graduate   
19149  Has relevent experience       no_enrollment         Masters   
19150  Has relevent experience       no_enrollment        Graduate   
19152  Has relevent experience       no_enrollment        Graduate   
19155  Has relevent experience       no_enrollment        Graduate   

      major_discipline experience company_size    company_type last_new_job  \
1                 STEM         15        50-99         Pvt Ltd           >4   
4                 STEM        >20        50-99  Funded Startup            4   
7                 STEM         13          <10         Pvt Ltd           >4   
8                 STEM          7        50-99         Pvt Ltd            1   
11                STEM          5    5000-9999         Pvt Ltd            1   
...                ...        ...          ...             ...          ...   
19147             STEM          1      100-500         Pvt Ltd            1   
19149             STEM          9        50-99         Pvt Ltd            1   
19150             STEM         10      100-500   Public Sector            3   
19152       Humanities          7        10/49  Funded Startup            1   
19155             STEM        >20        50-99         Pvt Ltd            4   

       training_hours  target  Outliers  
1                  47     0.0         0  
4                   8     0.0         0  
7                  18     1.0         0  
8                  46     1.0         0  
11                108     0.0         0  
...               ...     ...       ...  
19147              52     1.0         0  
19149              36     1.0         0  
19150              23     0.0         0  
19152              25     0.0         0  
19155              44     0.0         0  

[8955 rows x 15 columns]